apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observer
  template:
    metadata:
      labels:
        app: observer
    spec:
      containers:
        - name: observer
          image: observability_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8005