apiVersion: v1
kind: Service
metadata:
  name: observability_service
spec:
  type: NodePort
  selector:
    app: observer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8005
      nodePort: 30006