apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airflow-claim1
  name: airflow-claim1
  # namespace: stock-pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
