apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow_scheduler_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow_scheduler_service
  template:
    metadata:
      labels:
        app: airflow_scheduler_service
    spec:
      containers:
        - name: airflow_scheduler
          image: airflow_scheduler_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
