apiVersion: v1
kind: Service
metadata:
  name: airflow_scheduler_service
spec:
  type: NodePort
  selector:
    app: airflow_scheduler_service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007