scrape_configs:
  - job_name: 'airflow_service'
    static_configs:
      - targets: ['airflow:8080']

  - job_name: 'data_collector_service'
    static_configs:
      - targets: ['data_collector:8000']

  - job_name: 'database_writer_service'
    static_configs:
      - targets: ['database_writer:8001']

  - job_name: 'file_writer_service'
    static_configs:
      - targets: ['file_writer:8003']

  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['monitoring:8004']

  - job_name: 'observability_service'
    static_configs:
      - targets: ['observability:8005']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
