global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow:8080']
  - job_name: 'data_collector'
    static_configs:
      - targets: ['data_collector:8000']
  - job_name: 'data_processor'
    static_configs:
      - targets: ['data_processor:8001']
  - job_name: 'database_writer'
    static_configs:
      - targets: ['database_writer:8002']
  - job_name: 'file_writer'
    static_configs:
      - targets: ['file_writer:8003']
  - job_name: 'monitoring_service'
    static_configs:
      - targets: ['monitoring_service:8004']