apiVersion: apps/v1
kind: Deployment
metadata:
  name: database_writer_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database_writer
  template:
    metadata:
      labels:
        app: database_writer
    spec:
      containers:
        - name: database_writer
          image: database_writer_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002