apiVersion: v1
kind: Service
metadata:
  name: database_writer_service
spec:
  type: NodePort
  selector:
    app: database_writer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
      nodePort: 30003