apiVersion: v1
data:
  nginx.conf: events {} http { server { listen 80; location / { proxy_pass http://data-collector:8000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; } } }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: load-balancer
  name: load-balancer-cm0
