apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: monitoring
  name: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monitoring
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: monitoring
    spec:
      containers:
        - image: monitoring
          name: monitoring
          imagePullPolicy: Never
          ports:
            - containerPort: 8004
              protocol: TCP
      restartPolicy: Always
