apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: observability
  name: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: observability
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: observability
    spec:
      containers:
        - image: observability
          name: observability
          imagePullPolicy: Never
          ports:
            - containerPort: 8005
              protocol: TCP
      restartPolicy: Always
