apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitoring_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
        - name: monitor
          image: monitoring_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8004