apiVersion: v1
kind: Service
metadata:
  name: monitoring_service
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8004
      nodePort: 30005