apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file docker-compose.yml --out k8s-manifests
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: data-api-service
  name: data-api-service
spec:
  ports:
    - name: "8006"
      port: 8006
      targetPort: 8006
  selector:
    io.kompose.service: data-api-service
