apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-api-service-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      io.kompose.service: data-api-service  
  namespaceSelector:
    matchNames:
      - stock-pipeline
  endpoints:
    - port: http           
      path: /metrics
      interval: 15s
