apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-claim1
  namespace: stock-pipeline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed