apiVersion: v1
kind: ConfigMap
metadata:
  name: data-processor-config
  namespace: stock-pipeline
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  KAFKA_DAILY_TOPIC: "daily-data"
  KAFKA_15min_TOPIC: "15min-data"
  KAFKA_OPTION_TOPIC: "options-data"
  KAFKA_HISTORICAL_TOPIC: "historical-data"
  KAFKA_PROCESSED_DAILY: "processed-daily-data"
  KAFKA_PROCESSED_15MIN: "processed-15min-data"
  KAFKA_PROCESSED_OPTIONS: "processed-options-data"
  KAFKA_PROCESSED_HISTORICAL: "processed-historical-data"
  KAFKA_PROCESSED_FILE_DAILY: "processed-file-daily-data"
  KAFKA_PROCESSED_FILE_15MIN: "processed-file-15min-data"
  KAFKA_PROCESSED_FILE_OPTIONS: "processed-file-options-data"
  KAFKA_PROCESSED_FILE_HISTORICAL: "processed-file-historical-data"
  DJANGO_SECRET_KEY: "django-insecure-#2k^ti5^bcw_ce5-73!ce&w6ywg)6(_9gpceh+%!nqa^yp1=r6"
  APP_DEBUG: "True"