apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-writer-claim0
  namespace: stock-pipeline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Adjust size as needed