# kafka-init-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-init
  namespace: stock-pipeline
spec:
  template:
    spec:
      containers:
      - name: kafka-init
        image: confluentinc/cp-kafka:7.4.0
        command: ["/bin/bash", "-c"]
        args:
        - |
          for i in {1..30}; do
            kafka-broker-api-versions --bootstrap-server kafka:9092 && break
            echo 'Waiting for Kafka to be ready...'
            sleep 5
          done
          kafka-topics --create --topic daily-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic 15min-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic options-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic historical-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic processed-daily-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic processed-15min-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic processed-options-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          kafka-topics --create --topic processed-historical-data --bootstrap-server kafka:9092 --replication-factor 1 --partitions 5
          echo 'Kafka topics created!'
      restartPolicy: OnFailure