apiVersion: apps/v1
kind: Deployment
metadata:
  name: data_collector_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data_collector
  template:
    metadata:
      labels:
        app: data_collector
    spec:
      containers:
        - name: data_collector
          image: data_collector_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
