apiVersion: v1
kind: Service
metadata:
  name: data_collector_service
spec:
  type: NodePort
  selector:
    app: data_collector
  ports:
    - protocol: TCP
      port: 80                
      targetPort: 8001        
      nodePort: 30001