apiVersion: apps/v1
kind: Deployment
metadata:
  name: data_processor_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data_processor
  template:
    metadata:
      labels:
        app: data_processor
    spec:
      containers:
        - name: data_processor
          image: data_processor_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001