apiVersion: v1
kind: Service
metadata:
  name: data_processor_service
spec:
  type: NodePort
  selector:
    app: data_processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
      nodePort: 30002