apiVersion: apps/v1
kind: Deployment
metadata:
  name: file_writer_service_deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file_writer
  template:
    metadata:
      labels:
        app: file_writer
    spec:
      containers:
        - name: file_writer
          image: file_writer_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003