apiVersion: v1
kind: Service
metadata:
  name: file_writer_service
spec:
  type: NodePort
  selector:
    app: file_writer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
      nodePort: 30004