name: Microservices CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # - name: Build Backend Docker Image
      #   run: docker build -t backend-service ./Backend

      # - name: Build Frontend Docker Image
      #   run: docker build -t frontend-service ./Frontend

      # - name: Dummy Test
      #   run: echo "Tests will be added later"