name: CI Pipeline for Microservices

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - airflow_scheduler_service
          - data_api_service
          - data_collector_service
          - data_processor_service
          - database_writer_service
          - file_writer_service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd Backend/${{ matrix.service }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for test files and run tests
        run: |
          cd Backend/${{ matrix.service }}
          if find . -name "test*.py" -o -name "*_test.py" | grep -q .; then
            echo "Test files found, running tests..."
            python manage.py test
          else
            echo "No test files found, skipping tests for ${{ matrix.service }}"
          fi
        env:
          PYTHONPATH: ${{ github.workspace }}/Backend/${{ matrix.service }}


  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd Frontend/Stock_Analysis_Frontend
          npm install

      - name: Run Angular tests
        run: |
          cd Frontend/Stock_Analysis_Frontend
          npm run test -- --watch=false --browsers=ChromeHeadless


  build-docker-only:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Clean up Docker
        run: |
          docker system prune -f
          docker image prune -f

      - name: Show free memory and disk before build
        run: |
          echo "Disk usage:"
          df -h
          echo "Memory usage:"
          free -m

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          for service in airflow_scheduler_service data_api_service data_collector_service data_processor_service database_writer_service file_writer_service; do
            echo "Building Docker image for $service"
            ls -la Backend/$service
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service:test Backend/$service
            echo "Pushing Docker image for $service"
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service:test
          done

      - name: Show free memory and disk after build
        if: always()
        run: |
          echo "Disk usage after build:"
          df -h
          echo "Memory usage after build:"
          free -m